# Global build settings
[build]
  publish = ".next"
  command = "pnpm build"

[build.environment]
  NEXT_FORCE_EDGE_IMAGES = "true"
  NETLIFY_NEXT_DISABLE_ON_DEMAND_REVALIDATION = "true"
  NETLIFY_NEXT_DISABLE_INCREMENTAL_CACHE = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://esp.ethereum.foundation"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = "en/"
  [[plugins.inputs.audits]]
    path = "en/wallets/find-wallet/"
  [[plugins.inputs.audits]]
    path = "en/staking/"
  [[plugins.inputs.audits]]
    path = "en/whitepaper/"
  [[plugins.inputs.audits]]
    path = "en/nft/"
  [[plugins.inputs.audits]]
    path = "en/developers/docs/intro-to-ethereum/"
  [[plugins.inputs.audits]]
    path = "en/developers/tutorials/creating-a-wagmi-ui-for-your-contract/"

[functions]
  included_files = [
    "i18n.config.json",
    "src/intl/**/*",
    "src/data/mocks/**/*"
  ]
